# Matrices

A matrix is a rectangular grid of numbers, functions, symbols, or other mathematical expressions.

## 7.1 Tne structure of a matrix

Simply put. the products of inertia measure the misalignment between the object's angular momentum and its angualr velocity

### 7.1.1 Defining matrices in python

In [2]:
import numpy as np
from sympy import Matrix, sin, cos, symbols

A = np.array([[4, -1, 3], [5, 7, 2]])

p = symbols('p')
B = Matrix([[cos(p), -sin(p)], [sin(p), cos(p)]])
C_numpy = np.array([[1], [-1], [3]])
C_sympy = Matrix([[1], [-1], [3]])

print("A23 ", A[1,2])
print("B12 ", B[0, 1])

print(A)
print(B)
print(C_numpy)
print(C_sympy)

A23  2
B12  -sin(p)
[[ 4 -1  3]
 [ 5  7  2]]
Matrix([[cos(p), -sin(p)], [sin(p), cos(p)]])
[[ 1]
 [-1]
 [ 3]]
Matrix([[1], [-1], [3]])


### 7.1.2 Vectors as matrices

## 7.2 Matrix operations

### 7.2.1 Matrix equivalence

### 7.2.2 Multiplication by a scalar

### 7.2.3 Matrix addition

### 7.2.4 Matrix multiplication

### Example 7.2: Rotation of vectors with matrices

In [1]:
from sympy import Matrix, sin, cos, symbols, simplify
import pprint

phi1, phi2 = symbols('phi1, phi2')

R1 = Matrix([[cos(phi1),-sin(phi1)], [sin(phi1), cos(phi1)]])
R2 = Matrix([[cos(phi2),-sin(phi2)], [sin(phi2), cos(phi2)]])

R = R1 * R2
pp = pprint.PrettyPrinter(width=41, compact=True)
pp.pprint(simplify(R))

Matrix([
[cos(phi1 + phi2), -sin(phi1 + phi2)],
[sin(phi1 + phi2),  cos(phi1 + phi2)]])


### 7.2.5 Trace of a matrix

### 7.2.6 Tranpose and hermitian and joint of a matrix

### Example 7.3: The Pauli matrices

In [3]:
import numpy as np
from sympy import simplify

s_x = np.array([[0, 1], [1, 0]])
s_y = np.array([[0, -1j], [1j, 0]])
s_z = np.array([[1, 0], [0, -1]])

s_x_dagger = np.conjugate(np.transpose(s_x))
s_y_dagger = np.conjugate(np.transpose(s_y))
s_z_dagger = np.conjugate(np.transpose(s_z))

print(np.array_equal(s_x, s_x_dagger))
print(np.array_equal(s_y, s_y_dagger))
print(np.array_equal(s_z, s_z_dagger))

True
True
True


In [5]:
commut = simplify(s_x @ s_y - s_y @ s_x)
print(commut)
anti_commut = simplify(s_x @ s_y + s_y @ s_x)
print(anti_commut)

[[2.0*I, 0], [0, -2.0*I]]
[[0, 0], [0, 0]]


## 7.3 The determinant

### 7.3.1 Calculating determinants

### Example 7.4: The determinant of a $3\times 3$ matrix

In [13]:
from sympy import MatrixSymbol, simplify
from numpy import array, array_equal, linalg
C = array([[2,3,-1],[1,4,-2],[5,9,0]])
print('Determinant of C is ', linalg.det(C))

Determinant of C is  17.0


In [10]:
A = MatrixSymbol('A', 3, 3)
B = MatrixSymbol('B', 3, 3)

# make symbolic matrices into mutable matrices with explicit elements
Am = A.as_mutable()
Bm = B.as_mutable()

print(Am)
print(Bm)

print('The identity det(AB) = det(A)det(B) is: ', (array_equal(Am.det()*Bm.det(), Bm.det()*Am.det())))

Matrix([[A[0, 0], A[0, 1], A[0, 2]], [A[1, 0], A[1, 1], A[1, 2]], [A[2, 0], A[2, 1], A[2, 2]]])
Matrix([[B[0, 0], B[0, 1], B[0, 2]], [B[1, 0], B[1, 1], B[1, 2]], [B[2, 0], B[2, 1], B[2, 2]]])
The identity det(AB) = det(A)det(B) is:  True


In [15]:
print('The identity det(AB) = det(B)det(A) is: ', (array_equal((Am@Bm).det(), Bm.det()*Am.det())))
print('The identity det(AB) = det(A)det(B) is: ', (array_equal(simplify((Am@Bm).det()), simplify(Am.det()*Bm.det()))))

The identity det(AB) = det(B)det(A) is:  False
The identity det(AB) = det(A)det(B) is:  False


In [14]:
print(simplify((Am@Bm).det()))

A[0, 0]*A[1, 1]*A[2, 2]*B[0, 0]*B[1, 1]*B[2, 2] - A[0, 0]*A[1, 1]*A[2, 2]*B[0, 0]*B[1, 2]*B[2, 1] - A[0, 0]*A[1, 1]*A[2, 2]*B[0, 1]*B[1, 0]*B[2, 2] + A[0, 0]*A[1, 1]*A[2, 2]*B[0, 1]*B[1, 2]*B[2, 0] + A[0, 0]*A[1, 1]*A[2, 2]*B[0, 2]*B[1, 0]*B[2, 1] - A[0, 0]*A[1, 1]*A[2, 2]*B[0, 2]*B[1, 1]*B[2, 0] - A[0, 0]*A[1, 2]*A[2, 1]*B[0, 0]*B[1, 1]*B[2, 2] + A[0, 0]*A[1, 2]*A[2, 1]*B[0, 0]*B[1, 2]*B[2, 1] + A[0, 0]*A[1, 2]*A[2, 1]*B[0, 1]*B[1, 0]*B[2, 2] - A[0, 0]*A[1, 2]*A[2, 1]*B[0, 1]*B[1, 2]*B[2, 0] - A[0, 0]*A[1, 2]*A[2, 1]*B[0, 2]*B[1, 0]*B[2, 1] + A[0, 0]*A[1, 2]*A[2, 1]*B[0, 2]*B[1, 1]*B[2, 0] - A[0, 1]*A[1, 0]*A[2, 2]*B[0, 0]*B[1, 1]*B[2, 2] + A[0, 1]*A[1, 0]*A[2, 2]*B[0, 0]*B[1, 2]*B[2, 1] + A[0, 1]*A[1, 0]*A[2, 2]*B[0, 1]*B[1, 0]*B[2, 2] - A[0, 1]*A[1, 0]*A[2, 2]*B[0, 1]*B[1, 2]*B[2, 0] - A[0, 1]*A[1, 0]*A[2, 2]*B[0, 2]*B[1, 0]*B[2, 1] + A[0, 1]*A[1, 0]*A[2, 2]*B[0, 2]*B[1, 1]*B[2, 0] + A[0, 1]*A[1, 2]*A[2, 0]*B[0, 0]*B[1, 1]*B[2, 2] - A[0, 1]*A[1, 2]*A[2, 0]*B[0, 0]*B[1, 2]*B[2, 1] - 

### 7.3.2 Determinants as representations of area and volume

## Example 7.5: The Lorentz force

In [16]:
from numpy import array, cross
from sympy import symbols

Bx, By, Bz, vx, vy, vz, q = symbols('Bx, By, Bz, vx, vy, vz, q')

B = array([Bx, By, Bz])
v = array([vx, vy, vz])

F = q * cross(v, B)
print("The Lorentz force is F = ")
print(F)

print(F[0])
print(F[1])
print(F[2])

The Lorentz force is F = 
[q*(-By*vz + Bz*vy) q*(Bx*vz - Bz*vx) q*(-Bx*vy + By*vx)]
q*(-By*vz + Bz*vy)
q*(Bx*vz - Bz*vx)
q*(-Bx*vy + By*vx)


### 7.3.3 The Jacobian determinant and volume transformations

### Example 7.6: Example of using the Jacobian: The area of an ellipse

In [17]:
from sympy import symbols, integrate, diff, pi, simplify, sqrt
x, y, a, b, xprime, yprime = symbols('x, y, a, b, xprime, yprime', \
real=True)

x = a * xprime
y = b * yprime

J = diff(x, xprime)*diff(y,yprime)-diff(x,yprime)*diff(y, yprime)
print(simplify(J))

a*b


In [18]:
A = integrate(4*J, (yprime, 0, sqrt(1-xprime**2)), (xprime, 0, 1),)
print(A)

pi*a*b


## 7.4 Matrices and systems of Linear equations

### 7.4.1 Representing system of linear equations as a matrix equation

### Example 7.7: The inverse of a Matrix

In [21]:
from sympy import symbols, Matrix, simplify, solve
import pprint

pp = pprint.PrettyPrinter(width=41, compact=True)
a, b, c, d, e, f, x, y = symbols('a, b, c, d, e, f, x, y')
A = Matrix([[a, b], [c,d]])

det = A.det()
inverse = A.inv()

print('The inverse of A is: ')
pp.pprint(inverse)

print('The product inverseA*A is')
print(simplify(inverse*A))

The inverse of A is: 
Matrix([
[ d/(a*d - b*c), -b/(a*d - b*c)],
[-c/(a*d - b*c),  a/(a*d - b*c)]])
The product inverseA*A is
Matrix([[1, 0], [0, 1]])


In [22]:
sol = solve([a*x+b*y-e, c*x+d*y-f], (x, y))
print(sol[x])
print(sol[y])

(-b*f + d*e)/(a*d - b*c)
(a*f - c*e)/(a*d - b*c)


### 7.4.2 Representing systems of linear equations as an augmented matrix

### Example 7.8: Kirchhoff's laws for electronics

In [23]:
from sympy import Matrix
A = Matrix([[1,2,0,5],[0,2,-3,-5],[1,-1,-1,0]])

Ared = A.rref()[0]
print(A)
print(Ared)

Matrix([[1, 2, 0, 5], [0, 2, -3, -5], [1, -1, -1, 0]])
Matrix([[1, 0, 0, 35/11], [0, 1, 0, 10/11], [0, 0, 1, 25/11]])


### 7.4.3 Homogeneous equations

A system of n homogeneous equations with n unknowns has solutions other than the trivial solution, if and only if, the determinant of its coefficient matrix is equal to zero.

### Example 7.9: The normal modes of a two-mass three-spring system

In [24]:
from sympy import symbols, exp, I, diff, solve, expand, symbols, Matrix
import pprint
pp = pprint.PrettyPrinter(width=41, compact=True)

k, m, omega, x1, x2, A1, A2, t = \
symbols("k, m, omega, x1, x2, A1, A2, t")

x1 = A1*exp(I*omega*t)
x2 = A2*exp(I*omega*t)

eq1 =expand((m*diff(x1,t,t)+k*x1+k*(x1-x2))/exp(I*omega*t))
eq2 =expand((m*diff(x2,t,t)+k*x2+k*(x2-x1))/exp(I*omega*t))

# Matrix A has coefficients of A1, A2 in the system of equations
A = Matrix([[eq1.coeff(A1), eq1.coeff(A2)], [eq2.coeff(A1), eq2.coeff(A2)]])

pp.pprint(A)

Matrix([
[2*k - m*omega**2,               -k],
[              -k, 2*k - m*omega**2]])


In [25]:
# set determinant det(A)=0 and solve for omega
sol = solve(A.det(), omega)
print(sol[0])
print(sol[1])
print(sol[2])
print(sol[3])

-sqrt(3)*sqrt(k/m)
sqrt(3)*sqrt(k/m)
-sqrt(k/m)
sqrt(k/m)


## 7.5 Matrices as representations of linear operators

An operator is a mapping of a function from one space to another (possibly the same space). In fact, the derivative is a linear operator.

Another way of describing an operator is that an operator is a rule which provides instructions on what to do with its argument.

We will now look at a special type of transformation, the orthogonal transformations. A matrix R representing an orthogonal transformation is called an orthogonal matrix. A matrix R is orthogonal, if its inverse is equal to its tranpose.

### Example 7.10: The rotation matrix

In [27]:
from sympy import Matrix, simplify, cos, sin, symbols
import pprint
pp = pprint.PrettyPrinter(width=41, compact=True)

p, vx, vy = symbols('p, vx, vy')
# define matrices R, v
R = Matrix([[cos(p), -sin(p)], [sin(p), cos(p)]])
v = Matrix([vx, vy])

vprime = R @ v
pp.pprint(vprime)

print(simplify(R.det()))

Matrix([
[vx*cos(p) - vy*sin(p)],
[vx*sin(p) + vy*cos(p)]])
1


In [28]:
Rinv = R.inv()
pp.pprint(simplify(Rinv))

Matrix([
[ cos(p), sin(p)],
[-sin(p), cos(p)]])


In [29]:
pp.pprint(simplify(Rinv@R))

Matrix([
[1, 0],
[0, 1]])


In [31]:
print(simplify(vprime[0]**2+vprime[1]**2))

vx**2 + vy**2


## 7.6 Eigenvalues and eigenvectors

In classical mechanics, the eigenvectors of a rigid body's inertia tensor correspond to the body's axes of symmetry, and the eigenvalues are the moment of inertia about those axes. In quantum mechancis, eigenvectors correspond to potential states a particle can occupy after a measurement is made, while eigenvalues are potential results for a measurement.

In [33]:
from sympy import Matrix

A = Matrix([[2, 1], [1,2]])
print(A.eigenvals())

print(A.eigenvects()[0][2])
print(A.eigenvects()[1][2])

{3: 1, 1: 1}
[Matrix([
[-1],
[ 1]])]
[Matrix([
[1],
[1]])]


### Example 7.12: Ther inertia tensor of a cube

In [34]:
from sympy import Matrix, symbols

c = symbols('c')

A = Matrix([[8*c,-3*c,-3*c],[-3*c,8*c,-3*c],[-3*c,-3*c,8*c]])

print(A.eigenvals())

{2*c: 1, 11*c: 2}


In [35]:
print(A.eigenvects())

[(2*c, 1, [Matrix([
[1],
[1],
[1]])]), (11*c, 2, [Matrix([
[-1],
[ 1],
[ 0]]), Matrix([
[-1],
[ 0],
[ 1]])])]


## 7.7 Diagonalization of a matrix

Similar matrices have the same rank, trace, determinant, and eigenvalues